[tox]
basepython = py3
isolated_build = true
envlist =
    mlserver-{conda,venv}
    all-runtimes-{conda,venv}
    py3

[testenv]
allowlist_externals = poetry
set_env =
    GITHUB_SERVER_URL = {env:GITHUB_SERVER_URL:https\://github.com}
    GITHUB_REPOSITORY = {env:GITHUB_REPOSITORY:opendatahub-io/MLServer}
    GITHUB_REF        = {env:GITHUB_REF:refs/heads/master}
    conda: USE_CONDA = {env:USE_CONDA:true}
    venv:  USE_CONDA = {env:USE_CONDA:false}
passenv =
    DOCKER_HOST

[testenv:py3]
description = Run default pytest suite
commands_pre =
    poetry sync --no-root
commands =
    python -m pytest {posargs} -n auto

[testenv:mlserver-{conda,venv}]
description =
    conda: MLServer core tests with conda environment (USE_CONDA=true)
    venv:  MLServer core tests with venv environment (USE_CONDA=false)
commands_pre =
    poetry sync --no-root
commands =
    python -m pytest {posargs} -n auto \
        {toxinidir}/tests \
        --ignore={toxinidir}/tests/metrics \
        --ignore={toxinidir}/tests/kafka \
        --ignore={toxinidir}/tests/parallel \
        --ignore={toxinidir}/tests/grpc \
        --ignore={toxinidir}/tests/env \
        --ignore={toxinidir}/tests/cli
    # kafka and parallel tests are failing for macos when running in parallel
    # with the entire test suite. grpc, env, and cli tests are also flaky
    # when running in parallel. So, we run them separately.
    python -m pytest {posargs} \
        {toxinidir}/tests/metrics \
        {toxinidir}/tests/kafka \
        {toxinidir}/tests/parallel \
        {toxinidir}/tests/grpc \
        {toxinidir}/tests/env \
        {toxinidir}/tests/cli

[testenv:all-runtimes-{conda,venv}]
description =
    conda: All runtimes tests with conda environment (USE_CONDA=true)
    venv:  All runtimes tests with venv environment (USE_CONDA=false)
commands_pre =
    poetry sync --no-root \
        --with all-runtimes \
        --with all-runtimes-dev
commands =
    python -m pytest {posargs} -n auto \
        {toxinidir}/tests \
        {toxinidir}/runtimes/alibi-explain \
        {toxinidir}/runtimes/alibi-detect \
        {toxinidir}/runtimes/sklearn \
        {toxinidir}/runtimes/xgboost \
        {toxinidir}/runtimes/mllib \
        {toxinidir}/runtimes/lightgbm \
        {toxinidir}/runtimes/onnx \
        {toxinidir}/runtimes/mlflow \
        {toxinidir}/runtimes/huggingface \
        {toxinidir}/runtimes/catboost \
        --ignore={toxinidir}/tests/metrics \
        --ignore={toxinidir}/tests/kafka \
        --ignore={toxinidir}/tests/parallel \
        --ignore={toxinidir}/tests/grpc \
        --ignore={toxinidir}/tests/env \
        --ignore={toxinidir}/tests/cli
    # kafka and parallel tests are failing for macos when running in parallel
    # with the entire test suite. grpc, env, and cli tests are also flaky
    # when running in parallel. So, we run them separately.
    python -m pytest {posargs} \
        {toxinidir}/tests/metrics \
        {toxinidir}/tests/kafka \
        {toxinidir}/tests/parallel \
        {toxinidir}/tests/grpc \
        {toxinidir}/tests/env \
        {toxinidir}/tests/cli
set_env =
    {[testenv]set_env}
    TF_USE_LEGACY_KERAS = 1

[testenv:licenses]
description = Generate license reports for all dependencies
commands_pre =
    poetry sync --no-root \
        --with all-runtimes \
        --with all-runtimes-dev
commands =
  pip-licenses \
    --from=mixed \
    --format=csv \
    --output-file=./licenses/license_info.csv
  pip-licenses \
    --from=mixed \
    --format=plain-vertical \
    --with-license-file \
    --no-license-path \
    --output-file=./licenses/license.txt
