# generated by datamodel-codegen:
#   filename:  dataplane.yaml

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field, RootModel

from .base import BaseModel


class MetadataServerResponse(BaseModel):
    name: str
    version: str
    extensions: list[str]


class MetadataServerErrorResponse(BaseModel):
    error: str


class RuntimeSecurityMode(Enum):
    PRODUCTION = "PRODUCTION"
    DEVELOPMENT = "DEVELOPMENT"


class MetadataModelErrorResponse(BaseModel):
    error: str


class Parameters(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    content_type: str | None = None
    headers: dict[str, Any] | None = None


class TensorData(RootModel[list[Any] | Any]):
    root: list[Any] | Any = Field(..., title="TensorData")

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, idx):
        return self.root[idx]

    def __len__(self):
        return len(self.root)


class RequestOutput(BaseModel):
    name: str
    parameters: Parameters | None = None


class InferenceErrorResponse(BaseModel):
    error: str | None = None


class Datatype(Enum):
    BOOL = "BOOL"
    UINT8 = "UINT8"
    UINT16 = "UINT16"
    UINT32 = "UINT32"
    UINT64 = "UINT64"
    INT8 = "INT8"
    INT16 = "INT16"
    INT32 = "INT32"
    INT64 = "INT64"
    FP16 = "FP16"
    FP32 = "FP32"
    FP64 = "FP64"
    BYTES = "BYTES"


class RuntimeSecurityResponse(BaseModel):
    mode: RuntimeSecurityMode
    allowed_model_implementations: list[str] | None = Field(
        None, description="Allowed model implementations (production mode only)."
    )


class MetadataTensor(BaseModel):
    name: str
    datatype: Datatype
    shape: list[int]
    parameters: Parameters | None = None


class RequestInput(BaseModel):
    name: str
    shape: list[int]
    datatype: Datatype
    parameters: Parameters | None = None
    data: TensorData


class ResponseOutput(BaseModel):
    name: str
    shape: list[int]
    datatype: Datatype
    parameters: Parameters | None = None
    data: TensorData


class InferenceResponse(BaseModel):
    model_name: str
    model_version: str | None = None
    id: str | None = None
    parameters: Parameters | None = None
    outputs: list[ResponseOutput]


class MetadataModelResponse(BaseModel):
    name: str
    versions: list[str] | None = None
    platform: str
    inputs: list[MetadataTensor] | None = None
    outputs: list[MetadataTensor] | None = None
    parameters: Parameters | None = None


class InferenceRequest(BaseModel):
    id: str | None = None
    parameters: Parameters | None = None
    inputs: list[RequestInput]
    outputs: list[RequestOutput] | None = None
