# generated by datamodel-codegen:
#   filename:  model_repository.yaml

from enum import Enum

from pydantic import Field, RootModel

from .base import BaseModel


class RepositoryIndexRequest(BaseModel):
    ready: bool | None = None


class State(Enum):
    UNKNOWN = "UNKNOWN"
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    LOADING = "LOADING"
    UNLOADING = "UNLOADING"


class RepositoryIndexResponseItem(BaseModel):
    name: str
    version: str | None = None
    state: State
    reason: str


class RepositoryIndexResponse(RootModel[list[RepositoryIndexResponseItem]]):
    root: list[RepositoryIndexResponseItem] = Field(
        ..., title="RepositoryIndexResponse"
    )

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, idx):
        return self.root[idx]

    def __len__(self):
        return len(self.root)


class RepositoryLoadErrorResponse(BaseModel):
    error: str | None = None


class RepositoryUnloadErrorResponse(BaseModel):
    error: str | None = None
